# Generated by Django 3.1.5 on 2021-02-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mylist', '0002_auto_20210219_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='search',
            name='search',
            field=models.CharField(max_length=500),
        ),
    ]
